apiVersion: cloud-build-notifiers/v1
kind: SMTPNotifier
metadata:
  name: example-smtp-notifier
spec:
  notification:
    filter: build.status == Build.Status.SUCCESS
    delivery:
      server: smtp.gmail.com
      port: "587"
      sender: varunkumar.inbaraj@gmail.com
      from: varunkumar.inbaraj@gmail.com
      recipients:
        - ivarunkumar007@gmail.com
        # optional: more emails here
      password:
        secretRef: smtp-password
  secrets:
  - name: smtp-password
    value: projects/781150265673/secrets/f-passwd/versions/latest
