steps:
- name: gcr.io/cloud-builders/gcloud
  entrypoint: 'bash'
  args: [ '-c', "gcloud secrets versions access latest --secret=key_json --format='get(payload.data)' | tr '_-' '/+' | base64 -d > decrypted-data.txt" ]
  
- name: 'gcr.io/cloud-builders/gcloud'
  id: start-qliksrv-1-np
  entrypoint: 'bash'
  args: [ "gcloud compute instances start qliksrv-1 --zone=us-central1-a" ]
  

  
substitutions:
 _BUILDER_PROJECT: zenith-bi
 _DIR: .
 _ZONE: us-central1-a
 _SOURCE_DIR: autotest_compare/
 _USER_NAME: sapcc 
 _INSTANCE_NAME: qliksrv-1	 
 _DESTINATION_DIR: /work/ 
 _SSH_KEY_PATH: /builder/home/.ssh/google_compute_engine 
 _SCRIPT_NAME: autocmp-batch-script.sh  
 _REP_SCRIPT_NAME: send_report.py      
